package com.huskysoft.interviewannihilator.service;

import com.huskysoft.interviewannihilator.model.NetworkException;

import junit.framework.TestCase;

/**
 * The class <code>NetworkServiceTest</code> contains tests for the class
 * {@link <code>NetworkService</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 5/9/13 9:17 PM
 *
 * @author Bennett
 *
 * @version $Revision$
 */
public class NetworkServiceTest extends TestCase {
	
	private NetworkService networkService;

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public NetworkServiceTest(String name) {
		super(name);
		this.networkService = NetworkService.getInstance();
	}
	
	public void testGetAllQuestions() throws NetworkException {
		assertNotNull(networkService.getQuestions(null, null, 10, 0));
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = com.huskysoft.interviewannihilator.service
 * package.sourceFolder = InterviewAnnihilatorTest/src
 * superclassType = junit.framework.TestCase
 * testCase = NetworkServiceTest
 * testClassType = com.huskysoft.interviewannihilator.service.NetworkService
 */