package com.huskysoft.interviewannihilator.service;

import java.io.IOException;

import org.json.JSONException;
import com.huskysoft.interviewannihilator.model.NetworkException;
import com.huskysoft.interviewannihilator.util.PaginatedQuestions;
import com.huskysoft.interviewannihilator.util.PaginatedSolutions;

import junit.framework.TestCase;

/**
 * The class <code>QuestionServiceIntegrationTest</code> contains tests for the
 * class {@link <code>QuestionService</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 5/9/13 9:27 PM
 *
 * @author Bennett
 *
 * @version $Revision$
 */
public class QuestionServiceTest extends TestCase {

	private QuestionService questionService;

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public QuestionServiceTest(String name) {
		super(name);
		questionService = QuestionService.getInstance();
	}
	
	public void testGetAllQuestions() throws NetworkException, JSONException, IOException {
		PaginatedQuestions questions = questionService.getQuestions(null, null, 10, 0);
		System.out.println(questions);
	}
	
	public void testGetSolutions() throws NetworkException, JSONException, IOException {
		PaginatedSolutions solutions = questionService.getSolutions(10, 10, 0);
		System.out.println(solutions);
	}

}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = com.huskysoft.interviewannihilator.service
 * package.sourceFolder = InterviewAnnihilatorTest/src
 * superclassType = junit.framework.TestCase
 * testCase = QuestionServiceIntegrationTest
 * testClassType = com.huskysoft.interviewannihilator.service.QuestionService
 */